ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cats, except: [:destroy]

  get "/" , to: "cats#index"  

end

ninety-nine-cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ninety-nine-cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    require 'date'
    require 'action_view'
    include ActionView::Helpers::DateHelper

    CAT_COLORS = ['orange', 'red', 'brown', 'tan']
    SEX = ['M', 'F']

    validates :birth_date, presence: true
    validates :color, presence: true
    validates :name, presence: true
    validates :sex, presence: true

    validate :inclusion_color
    validate :inclusion_sex 
    validate :birth_date_cannot_be_in_future

    def inclusion_color
        if !CAT_COLORS.include?(self.color)
            errors.add(:color, "must be within valid cat colors")
        end
    end

    def inclusion_sex
        if !SEX.include?(self.sex)
            errors.add(:sex, "must be either M or F representing Male or Female")
        end
    end

    def birth_date_cannot_be_in_future
        if birth_date.present? && birth_date > Date.today
            errors.add(:birth_date, "cannot be in the future and must have been born by today")
        end
    end

    def age
        time_ago_in_words(birth_date)
    end
end

ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController 

    def index
        @cats = Cat.all 

        render :index
    end

    def show 
        @cat = Cat.find(params[:id]) 

        if @cat.save
            render :show 
        else 
           render @cat.errors.full_messages, status: 404 
        end 
    end 

    def create
        @cat = Cat.new(cat_params)

        if @cat.save
            render :show 
        else
            render @cat.errors.full_messages, status: 422
        end
    end

    private 

    def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end 

end 

ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety-nine-cats/app/views/cats/index.html.erb
<% @cats.each do |cat| %>

<ul>
    <li>
        <%= cat.name %>
    </li>
        <li>
            <a href="<%= cat_url(cat) %>" > Show Cat</a>
        </li>
</ul>

<%end%>

ninety-nine-cats/app/views/cats/show.html.erb
<%=@cat.name%>
<table>
    <thead> 
    <tr>
        <th colspan="1">Attribute</th> 
        <th colspan="1">Value</th> 
    </tr>
    </thead>
    <tbody>
        <tr> 
            <td>age</td> 
            <td><%=@cat.age%></td>
        </tr> 
        <tr> 
            <td>birth_date</td> 
            <td><%=@cat.birth_date%></td>
        </tr>
        <tr>
            <td>color</td> 
            <td><%=@cat.color%></td>
        </tr> 
        <tr>
            <td>sex</td> 
            <td><%=@cat.sex%></td>
        </tr>
    </tbody>
    <thead>
        <tr>
            <th colspan="2">Description</th>    
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="2" ><%=@cat.description%></td>
        </tr>
    </tbody>
</table>

ninety-nine-cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ninety-nine-cats/app/views/layouts/show.html.erb
<%=@cat.name%>
<table>
    <thead> 
    <tr>
        <th colspan="1">Attribute</th> 
        <th colspan="1">Value</th> 
    </tr>
    </thead>
    <tbody>
        <tr> 
            <td>age</td> 
            <td><%=@cat.age%></td>
        </tr> 
        <tr> 
            <td>birth_date</td> 
            <td><%=@cat.birth_date%></td>
        </tr>
        <tr>
            <td>color</td> 
            <td><%=@cat.color%></td>
        </tr> 
        <tr>
            <td>sex</td> 
            <td><%=@cat.sex%></td>
        </tr>
    </tbody>
    <thead>
        <tr>
            <th colspan="1">Description</th>    
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%=@cat.description%></td>
        </tr>
    </tbody>
</table>